# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:22-slim AS builder

# Set the working directory
WORKDIR /app

# Copy necessary files for installing dependencies and building the project
COPY package.json pnpm-lock.yaml ./
COPY tsconfig.json ./
COPY src ./src

# Install pnpm package manager
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Build the project
RUN pnpm run build

# Build Smithery HTTP bundle
RUN npx -y @smithery/cli build -o .smithery/index.cjs

# Stage 2: Run
FROM node:22-slim

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.smithery ./.smithery
COPY package.json pnpm-lock.yaml ./

# Install package manager and only production dependencies
RUN npm install -g pnpm \
  && pnpm install --prod --ignore-scripts

# Set environment variable for Google credentials
ENV GOOGLE_APPLICATION_CREDENTIALS=credentials.json
ENV PORT=3000

# Define the command to run the application
CMD ["node", ".smithery/index.cjs"]
